version: '3'

services:
  concourse-db:
    image: postgres
    dns: 8.8.8.8
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    dns: 8.8.8.8
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_ADD_LOCAL_USER: hagen:D1stributiv
      CONCOURSE_MAIN_TEAM_LOCAL_USER: hagen
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    dns: 8.8.8.8
    environment:
      - CONCOURSE_TSA_HOST=concourse-web:2222

